Phrase.delete_all
List.delete_all
Section.delete_all
Topic.delete_all

opto = Topic.create!(name: 'Optometry')


pre = Section.create!(name: 'Pre-Exam', topic: opto)
exam = Section.create!(name: 'Exam', topic: opto)
postexam = Section.create!(name: 'Post-Exam', topic: opto)

case_history = List.create!(name: 'Case History', section: pre)
preliminaries = List.create!(name: 'Preliminaries', section: pre)
phorias = List.create!(name: 'Phorias', section: exam)
ishihara = List.create!(name: 'Ishihara Test Numbers', section: exam)
helpful_words = List.create!(name: 'Helpful Words and Phrases', section: pre)
followup = List.create!(name: 'Follow-Up', section: postexam)
internals = List.create!(name: 'Internals', section: exam)
history = List.create!(name: 'History', section: pre)
biomicroscopy = List.create!(name: 'Biomicroscopy', section: exam)
visual_acuity = List.create!(name: 'Visual Acuity', section: exam)
keratometry = List.create!(name: 'Keratometry', section: exam)
static = List.create!(name: 'Static', section: exam)
pinhole = List.create!(name: 'Pinhole', section: exam)

Phrase.create!(english: 'I am going to examine the eye.', traditional: '我現在要檢查眼睛。', pinyin: 'wǒ xiàn zài yào jiǎn chá yǎn jīng', list: biomicroscopy)
Phrase.create!(english: 'Close your eyes.', traditional: '閉眼睛。', pinyin: 'bì yǎn jīng', list: biomicroscopy)
Phrase.create!(english: 'Open your eyes more.', traditional: '把你的眼睛打開多一點。', pinyin: 'bǎ nǐ de yǎn jīng dǎ kāi duō yī diǎn', list: biomicroscopy)
Phrase.create!(english: 'I am going to examine the eyelids.', traditional: '我現在要檢查眼皮。', pinyin: 'wǒ xiàn zài yào jiǎn chá yǎn pí', list: biomicroscopy)
Phrase.create!(english: 'Look down.', traditional: '往下看。', pinyin: 'wǎng xià kàn', list: biomicroscopy)
Phrase.create!(english: 'Look up.', traditional: '往上看。', pinyin: 'wǎng shàng kàn', list: biomicroscopy)
Phrase.create!(english: 'Blink.', traditional: '眨眼睛。', pinyin: 'zhǎ yǎn jīng', list: biomicroscopy)
Phrase.create!(english: 'Good morning.', traditional: '早安。', pinyin: 'zǎo ān', list: case_history)
Phrase.create!(english: 'Good afternoon.', traditional: '午安。', pinyin: 'wǔ ān', list: case_history)
Phrase.create!(english: 'What is your name?', traditional: '你叫甚麼名字？', pinyin: 'nǐ jiào shén me míng zì', list: case_history)
Phrase.create!(english: 'My name is...', traditional: '我的名字是。。。', pinyin: 'wǒ de míng zì shì', list: case_history)
Phrase.create!(english: 'I only speak a little Chinese.', traditional: '我只能說一點中文。', pinyin: 'wǒ zhǐ néng shuō yī diǎn zhōng wén', list: case_history)
Phrase.create!(english: 'Please limit your answers to yes or no when possible.', traditional: '你只需要回答是或不是', pinyin: 'nǐ zhǐ xū yào huí dá shì huò bú shì', list: case_history)
Phrase.create!(english: 'Have you been here before?', traditional: '你以前來過這裡嗎？', pinyin: 'nǐ yǐ qián lái guò zhè lǐ ma', list: case_history)
Phrase.create!(english: 'How long ago?', traditional: '多久之前？', pinyin: 'duō jiǔ zhī qián', list: case_history)
Phrase.create!(english: 'Please write your address here.', traditional: '請寫下你的地址。', pinyin: 'qǐng xiě xià nǐ de dì zhǐ', list: case_history)
Phrase.create!(english: 'How old are you?', traditional: '你幾歲？', pinyin: 'nǐ jǐ suì', list: case_history)
Phrase.create!(english: 'When was your last eye exam? One, two, or three years?', traditional: '你上次眼睛檢查是什麼時候？一年，兩年，還是三年？', pinyin: 'nǐ shàng cì yǎn jīng jiǎn chá shì shén me shí hòu   yī nián liǎng nián   hái shì sān nián', list: case_history)
Phrase.create!(english: 'Do you use glasses or contacts?', traditional: '你是用眼鏡還是隱形眼鏡？', pinyin: 'nǐ shì yòng yǎn jìng hái shì yǐn xíng yǎn jìng', list: case_history)
Phrase.create!(english: 'Do you use them for seeing far away or up close?', traditional: '你用眼鏡是為了近視還是遠視？', pinyin: 'nǐ yòng yǎn jìng shì wèi le jìn shì hái shì yuǎn shì', list: case_history)
Phrase.create!(english: 'Do you have a problem seeing at a distance?', traditional: '你看遠有沒有問題？', pinyin: 'nǐ kàn yuǎn yǒu méi yǒu wèn tí', list: case_history)
Phrase.create!(english: 'While reading?', traditional: '閱讀時呢？', pinyin: 'yuè dú shí ne', list: case_history)
Phrase.create!(english: 'How long has it been since you noticed this problem?', traditional: '你發現這個問題多久了？', pinyin: 'nǐ fā xiàn zhè gè wèn tí duō jiǔ le', list: case_history)
Phrase.create!(english: 'Show me at what distance you read.', traditional: '你閱讀時需要多少距離。', pinyin: 'nǐ yuè dú shí xū yào duō shǎo jù lí', list: case_history)
Phrase.create!(english: 'Do you get headaches?', traditional: '你會不會頭痛？', pinyin: 'nǐ huì bù huì tóu tòng', list: case_history)
Phrase.create!(english: 'Show me in what part of the head hurts.', traditional: '告訴我你頭哪邊痛。', pinyin: 'gào sù wǒ nǐ tóu nǎ biān tòng', list: case_history)
Phrase.create!(english: 'In the morning, afternoon, or evening?', traditional: '在早晨，下午，還是晚上？', pinyin: 'zài zǎo chén   xià wǔ   hái shì wǎn shàng', list: case_history)
Phrase.create!(english: 'When you read?', traditional: '那你閱讀的時候會不會頭痛？', pinyin: 'nà nǐ yuè dú de shí hòu huì bù huì tóu tòng', list: case_history)
Phrase.create!(english: 'At work （ school ） ,at home, or both places?', traditional: '在工作時（學校），在家，還是都會？', pinyin: 'zài gōng zuò shí   xué xiào     zài jiā   hái shì dū huì', list: case_history)
Phrase.create!(english: 'Do you get pain in your eyes?', traditional: '你眼睛會不會痛？', pinyin: 'nǐ yǎn jīng huì bù huì tòng', list: case_history)
Phrase.create!(english: 'Always?', traditional: '常常？', pinyin: 'cháng cháng', list: case_history)
Phrase.create!(english: 'Sometimes?', traditional: '有時候？', pinyin: 'yǒu shí hòu', list: case_history)
Phrase.create!(english: 'Since when did it begin?', traditional: '從甚麼時候開始？', pinyin: 'cóng shén me shí hòu kāi shǐ', list: case_history)
Phrase.create!(english: 'Has it become worse?', traditional: '有沒有變的更糟？', pinyin: 'yǒu méi yǒu biàn de gèng zāo', list: case_history)
Phrase.create!(english: 'During the morning?', traditional: '早晨時？', pinyin: 'zǎo chén shí', list: case_history)
Phrase.create!(english: 'In the afternoon?', traditional: '下午時？', pinyin: 'xià wǔ shí', list: case_history)
Phrase.create!(english: 'At night?', traditional: '晚上時？', pinyin: 'wǎn shàng shí', list: case_history)
Phrase.create!(english: 'Do your eyes ever itch?', traditional: '你的眼睛會不會癢癢的？', pinyin: 'nǐ de yǎn jīng huì bù huì yǎng yǎng de', list: case_history)
Phrase.create!(english: 'Do your eyes ever burn?', traditional: '你的眼睛會不會灼痛？', pinyin: 'nǐ de yǎn jīng huì bù huì zhuó tòng', list: case_history)
Phrase.create!(english: 'Do your eyes ever tear?', traditional: '你的眼睛會不會流淚？', pinyin: 'nǐ de yǎn jīng huì bù huì liú lèi', list: case_history)
Phrase.create!(english: 'Have you ever injured your eyes?', traditional: '你眼睛有沒有受過傷？', pinyin: 'nǐ yǎn jīng yǒu méi yǒu shòu guò shāng', list: case_history)
Phrase.create!(english: 'In what eye?', traditional: '在哪一個眼睛？', pinyin: 'zài nǎ yī gè yǎn jīng', list: case_history)
Phrase.create!(english: 'Was it a blow to the eye?', traditional: '你的眼睛是不是被打的？', pinyin: 'nǐ de yǎn jīng shì bú shì bèi dǎ dí', list: case_history)
Phrase.create!(english: 'A cut?', traditional: '有沒有傷口?', pinyin: 'yǒu méi yǒu shāng kǒu', list: case_history)
Phrase.create!(english: 'Or did something enter your eye?', traditional: '或者是有東西近入你的眼睛?', pinyin: 'huò zhě shì yǒu dōng xī jìn rù nǐ de yǎn jīng', list: case_history)
Phrase.create!(english: 'Have you ever had any disease in the eye?', traditional: '你的眼睛得過病嗎？', pinyin: 'nǐ de yǎn jīng dé guò bìng ma', list: case_history)
Phrase.create!(english: 'Glaucoma?', traditional: '青光眼？', pinyin: 'qīng guāng yǎn', list: case_history)
Phrase.create!(english: 'Cataracts?', traditional: '白內障？', pinyin: 'bái nèi zhàng', list: case_history)
Phrase.create!(english: 'Infection?', traditional: '感染？', pinyin: 'gǎn rǎn', list: case_history)
Phrase.create!(english: 'Have you ever had eye surgery?', traditional: '你的眼睛動過手術嗎？', pinyin: 'nǐ de yǎn jīng dòng guò shǒu shù ma', list: case_history)
Phrase.create!(english: 'When?', traditional: '什麼時候?', pinyin: 'shén me shí hòu', list: case_history)
Phrase.create!(english: 'For cataracts?', traditional: '為了白內障?', pinyin: 'wèi le bái nèi zhàng', list: case_history)
Phrase.create!(english: 'Myopia?', traditional: '近視?', pinyin: 'jìn shì', list: case_history)
Phrase.create!(english: 'For something that entered the eye?', traditional: '是因為有東西近入你的眼睛嗎?', pinyin: 'shì yīn wèi yǒu dōng xī jìn rù nǐ de yǎn jīng ma', list: case_history)
Phrase.create!(english: 'Strabismus?', traditional: '斜視？', pinyin: 'xié shì', list: case_history)
Phrase.create!(english: 'When was your last medical exam, one or two years ago?', traditional: '你上次檢查眼睛是什麼時候？一年前還是兩年前？', pinyin: 'nǐ shàng cì jiǎn chá yǎn jīng shì shén me shí hòu   yī nián qián hái shì liǎng nián qián', list: case_history)
Phrase.create!(english: 'Are you taking any medicine?', traditional: '你現在有沒有固定用藥？', pinyin: 'nǐ xiàn zài yǒu méi yǒu gù dìng yòng yào', list: case_history)
Phrase.create!(english: 'Please write your name here.', traditional: '請把你的名字寫下來。', pinyin: 'qǐng bǎ nǐ de míng zì xiě xià lái', list: case_history)
Phrase.create!(english: 'Since when are you taking it?', traditional: '你從什麼時候開始用?', pinyin: 'nǐ cóng shén me shí hòu kāi shǐ yòng', list: case_history)
Phrase.create!(english: 'What do you take it for?', traditional: '你為什麼要吃這些藥?', pinyin: 'nǐ wèi shén me yào chī zhè xiē yào', list: case_history)
Phrase.create!(english: 'Is there a possibility of you being pregnant?', traditional: '你可不可能懷孕了?', pinyin: 'nǐ kě bù kě néng huái yùn le', list: case_history)
Phrase.create!(english: 'Do you take contraceptives?', traditional: '你有沒有用避孕品？', pinyin: 'nǐ yǒu méi yǒu yòng bì yùn pǐn', list: case_history)
Phrase.create!(english: 'Do you have or ever had:', traditional: '你有沒有還是從來有過：', pinyin: 'nǐ yǒu méi yǒu hái shì cóng lái yǒu guò', list: case_history)
Phrase.create!(english: 'Diabetes?', traditional: '糖尿病？', pinyin: 'táng niào bìng', list: case_history)
Phrase.create!(english: 'Kidney problems?', traditional: '腎臟問題？', pinyin: 'shèn zàng wèn tí', list: case_history)
Phrase.create!(english: 'Thyroid problems?', traditional: '甲狀問題？', pinyin: 'jiǎ zhuàng wèn tí', list: case_history)
Phrase.create!(english: 'High blood pressure?', traditional: '高血壓？', pinyin: 'gāo xuè yā', list: case_history)
Phrase.create!(english: 'Do you have allergies to any medicines?', traditional: '你有沒有對什麼藥過敏?', pinyin: 'nǐ yǒu méi yǒu duì shén me yào guò mǐn', list: case_history)
Phrase.create!(english: 'Which one?', traditional: '對哪一個?', pinyin: 'duì nǎ yī gè', list: case_history)
Phrase.create!(english: 'Do you have sinus problems?', traditional: '你有沒有瘺的問題？', pinyin: 'nǐ yǒu méi yǒu lòu de wèn tí', list: case_history)
Phrase.create!(english: 'Follow me please.', traditional: '請跟我來。', pinyin: 'qǐng gēn wǒ lái', list: helpful_words)
Phrase.create!(english: 'I don\'t understand.', traditional: '我不懂。', pinyin: 'wǒ bù dǒng', list: helpful_words)
Phrase.create!(english: 'Do you understand?', traditional: '你懂不懂。', pinyin: 'nǐ dǒng bù dǒng', list: helpful_words)
Phrase.create!(english: 'Speak slower please.', traditional: '請說話慢一點。', pinyin: 'qǐng shuō huà màn yī diǎn', list: helpful_words)
Phrase.create!(english: 'Look.', traditional: '看。', pinyin: 'kàn', list: helpful_words)
Phrase.create!(english: 'Here.', traditional: '這裡。', pinyin: 'zhè lǐ', list: helpful_words)
Phrase.create!(english: 'Chin', traditional: '下吧', pinyin: 'xià ba', list: helpful_words)
Phrase.create!(english: 'Forehead', traditional: '額頭', pinyin: 'é tóu', list: helpful_words)
Phrase.create!(english: 'Eye', traditional: '眼睛', pinyin: 'yǎn jīng', list: helpful_words)
Phrase.create!(english: 'Left', traditional: '左', pinyin: 'zuǒ', list: helpful_words)
Phrase.create!(english: 'Right', traditional: '右', pinyin: 'yòu', list: helpful_words)
Phrase.create!(english: 'Light', traditional: '光', pinyin: 'guāng', list: helpful_words)
Phrase.create!(english: 'Drops (eye drops)', traditional: '眼藥', pinyin: 'yǎn yào', list: helpful_words)
Phrase.create!(english: 'Pupil', traditional: '瞳孔', pinyin: 'tóng kǒng', list: helpful_words)
Phrase.create!(english: 'Iris', traditional: '虹膜', pinyin: 'hóng mó', list: helpful_words)
Phrase.create!(english: 'Retina', traditional: '視網膜', pinyin: 'shì wǎng mó', list: helpful_words)
Phrase.create!(english: 'Glasses', traditional: '眼鏡', pinyin: 'yǎn jìng', list: helpful_words)
Phrase.create!(english: 'Sunglasses', traditional: '太陽眼鏡', pinyin: 'tài yáng yǎn jìng', list: helpful_words)
Phrase.create!(english: 'Bifocals', traditional: '雙光眼鏡', pinyin: 'shuāng guāng yǎn jìng', list: helpful_words)
Phrase.create!(english: 'Trifocals', traditional: '三焦距眼鏡', pinyin: 'sān jiāo jù yǎn jìng', list: helpful_words)
Phrase.create!(english: 'Good morning. Sit down, please.', traditional: '早安。請坐。', pinyin: 'zǎo ān   qǐng zuò', list: history)
Phrase.create!(english: 'I\'m Doctor Chan.', traditional: '我是陳醫生。', pinyin: 'wǒ shì chén yī shēng', list: history)
Phrase.create!(english: 'How are you?', traditional: '你好嗎?', pinyin: 'nǐ hǎo ma', list: history)
Phrase.create!(english: 'I speak only a little Chinese, and for that reason, I want you to speak slowly and limit your answers to that which I ask you.', traditional: '我只能說一點中文，所以請您慢慢說話，並確切回答我的問題。', pinyin: 'wǒ zhǐ néng shuō yī diǎn zhōng wén   suǒ yǐ qǐng nín màn màn shuō huà bìng què qiè huí dá wǒ de wèn tí', list: history)
Phrase.create!(english: 'When did you have your last eye examination?', traditional: '你上次做眼睛檢查是甚麼時候？', pinyin: 'nǐ shàng cì zuò yǎn jīng jiǎn chá shì shén me shí hòu', list: history)
Phrase.create!(english: 'When was the last time your eyeglass prescription was changed?', traditional: '你最近一次眼睛度數變動是什麼時候？', pinyin: 'nǐ zuì jìn yī cì yǎn jīng dù shù biàn dòng shì shén me shí hòu', list: history)
Phrase.create!(english: 'Can you see things well at near?', traditional: '你看近的東西清不清楚？', pinyin: 'nǐ kàn jìn de dōng xī qīng bù qīng chǔ', list: history)
Phrase.create!(english: 'Can you see things which are far away?', traditional: '你看遠的東西清不清楚？', pinyin: 'nǐ kàn yuǎn de dōng xī qīng bù qīng chǔ', list: history)
Phrase.create!(english: 'Do you get headaches? Migraines?', traditional: '你會不會頭痛？偏頭痛？', pinyin: 'nǐ huì bù huì tóu tòng   piān tóu tòng', list: history)
Phrase.create!(english: 'Do you often get headaches?', traditional: '你會不會常常頭痛？', pinyin: 'nǐ huì bù huì cháng cháng tóu tòng', list: history)
Phrase.create!(english: 'Where does it hurt?', traditional: '那裡痛？', pinyin: 'nà lǐ tòng', list: history)
Phrase.create!(english: 'Does it hurt only in one spot or all over your head?', traditional: '只是一個地方痛還是整個頭都痛？', pinyin: 'zhǐ shì yī gè dì fāng tòng hái shì zhěng gè tóu dōu tòng', list: history)
Phrase.create!(english: 'At what time of day do you have these headaches?', traditional: '一天之內你甚麼時候會頭痛？', pinyin: 'yī tiān zhī nèi nǐ shén me shí hòu huì tóu tòng', list: history)
Phrase.create!(english: 'How serious is the pain? Is the pain sharp or dull?', traditional: '很嚴重的頭痛嗎？是很刺激的還是些微的？', pinyin: 'hěn yán zhòng de tóu tòng ma   shì hěn cì jī de hái shì xiē wēi de', list: history)
Phrase.create!(english: 'Does your head throb?', traditional: '你的頭會不會抽痛？', pinyin: 'nǐ de tóu huì bù huì chōu tòng', list: history)
Phrase.create!(english: 'Does it get worse when you lie down?', traditional: '你躺著會不會更嚴重？', pinyin: 'nǐ tǎng zhù huì bù huì gèng yán zhòng', list: history)
Phrase.create!(english: 'Do you see lights or spots of color?', traditional: '你有沒有看到光或者是色點？', pinyin: 'nǐ yǒu méi yǒu kàn dào guāng huò zhě shì sè diǎn', list: history)
Phrase.create!(english: 'Do you see rays or colored arcs around the lights?', traditional: '你可以清楚看到光的輪廓還是模糊的?', pinyin: 'nǐ kě yǐ qīng chǔ kàn dào guāng de lún kuò hái shì mó hú de', list: history)
Phrase.create!(english: 'Does it get better if you take aspirin?', traditional: '你吃阿斯匹𩆜之後有沒有好一點？', pinyin: 'nǐ chī ā sī pǐ     zhī hòu yǒu méi yǒu hǎo yī diǎn', list: history)
Phrase.create!(english: 'Do your eyes burn, sting, water, or itch very much?', traditional: '你的眼睛會不會有灼熱感，刺刺的，濕濕的還是癢癢的？', pinyin: 'nǐ de yǎn jīng huì bù huì yǒu zhuó rè gǎn cì cì de shī shī de hái shì yǎng yǎng de', list: history)
Phrase.create!(english: 'Do you see double? When?', traditional: '你看東西時會不會有重疊的影像？甚麼時候？', pinyin: 'nǐ kàn dōng xī shí huì bù huì yǒu chóng dié de yǐng xiàng   shén me shí hòu', list: history)
Phrase.create!(english: 'Have you received any injury to your eyes, or was surgery performed on your eyes?', traditional: '你的眼睛有沒有受過傷嗎或者是動過手術？', pinyin: 'nǐ de yǎn jīng yǒu méi yǒu shòu guò shāng ma huò zhě shì dòng guò shǒu shù', list: history)
Phrase.create!(english: 'How is your general health? Do you have problems with glaucoma, diabetes, high blood pressure, kidney disorders, epilepsy, or allergies?', traditional: '你平常身體如何？你有沒有青光眼,糖尿病，高血壓，腎臟問題，癲癇還是對什麼東西有過敏症狀？', pinyin: 'nǐ píng cháng shēn tǐ rú hé   nǐ yǒu méi yǒu qīng guāng yǎn táng niào bìng   gāo xuè yā   shèn zàng wèn tí   diān xián hái shì duì shén me dōng xī yǒu guò mǐn zhèng zhuàng', list: history)
Phrase.create!(english: 'Does anyone in your family suffer from eye problems, glaucoma, diabetes, high blood pressure, kidney problems, or epilepsy?', traditional: '你的家人有沒有青光眼，糖尿病，高血壓，腎臟問題，癲癇還是其它的眼睛疾病？', pinyin: 'nǐ de jiā rén yǒu méi yǒu qīng guāng yǎn   táng niào bìng   gāo xuè yā   shèn zàng wèn tí   diān xián hái shì qí tā de yǎn jīng jí bìng', list: history)
Phrase.create!(english: 'Are you taking any medication? (drops, ointments, capsules, pills)', traditional: '你現在有沒有固定用藥？（眼藥水，藥膏，膠囊，藥丸）', pinyin: 'nǐ xiàn zài yǒu méi yǒu gù dìng yòng yào     yǎn yào shuǐ   yào gāo   jiāo náng   yào wán', list: history)
Phrase.create!(english: 'Do you feel something in your eye?', traditional: '你覺得有沒有東西在眼睛𥚃面?', pinyin: 'nǐ jué dé yǒu méi yǒu dōng xī zài yǎn jīng  li  miàn', list: history)
Phrase.create!(english: 'Do you have any allergies?', traditional: '你有沒有過敏症狀？', pinyin: 'nǐ yǒu méi yǒu guò mǐn zhèng zhuàng', list: history)
Phrase.create!(english: 'Are you allergic to certain medicines?', traditional: '你有沒有對哪些藥物過敏？', pinyin: 'nǐ yǒu méi yǒu duì nǎ xiē yào wù guò mǐn', list: history)
Phrase.create!(english: 'For what reason do you take the medicines?', traditional: '你為什麼要吃這些藥？', pinyin: 'nǐ wèi shén me yào chī zhè xiē yào', list: history)
Phrase.create!(english: 'Do you drink a lot of alcohol?', traditional: '你平常有沒有喝很多酒？', pinyin: 'nǐ píng cháng yǒu méi yǒu hē hěn duō jiǔ', list: history)
Phrase.create!(english: 'Do you smoke? How much?', traditional: '你有沒有抽煙？多少量？', pinyin: 'nǐ yǒu méi yǒu chōu yān   duō shǎo liàng', list: history)
Phrase.create!(english: 'Do you take narcotics or sedatives or both?', traditional: '你有沒有習慣用麻醉藥、鎮定劑，還是兩種都用？', pinyin: 'nǐ yǒu méi yǒu xí guàn yòng má zuì yào   zhèn dìng jì   hái shì liǎng zhǒng dōu yòng', list: history)
Phrase.create!(english: 'Are you nervous?', traditional: '你會緊張嗎？', pinyin: 'nǐ huì jǐn zhāng ma', list: history)
Phrase.create!(english: 'Have you been under a doctor\'s care before?', traditional: '你以前有看過眼科醫生嗎？', pinyin: 'nǐ yǐ qián yǒu kàn guò yǎn kē yī shēng ma', list: history)
Phrase.create!(english: 'What is his name, address, and telephone number?', traditional: '他的名字，地址，和電話號碼是甚麼？', pinyin: 'tā de míng zì   dì zhǐ   hé diàn huà hào mǎ shì shén me', list: history)
Phrase.create!(english: 'How old are you?', traditional: '你現在幾歲？', pinyin: 'nǐ xiàn zài jǐ suì', list: history)
Phrase.create!(english: 'Please take off your glasses.', traditional: '請你把眼鏡拿掉。', pinyin: 'qǐng nǐ bǎ yǎn jìng ná diào', list: history)
Phrase.create!(english: 'Please put them on.', traditional: '請戴起來。', pinyin: 'qǐng dài qǐ lái', list: history)
Phrase.create!(english: 'Describe (show me) what you see.', traditional: '請描述（告訴我）你看到的東西。', pinyin: 'qǐng miáo shù   gào sù wǒ   nǐ kàn dào de dōng xī', list: history)
Phrase.create!(english: 'Do you see lightning flashes or lights and stars above the objects?', traditional: '你有沒有看到閃光還是亮點在物體上面？', pinyin: 'nǐ yǒu méi yǒu kàn dào shǎn guāng hái shì liàng diǎn zài wù tǐ shàng miàn', list: history)
Phrase.create!(english: 'Is it fleeting or is it constant?', traditional: '是暫時的還是持久的？', pinyin: 'shì zàn shí de hái shì chí jiǔ de', list: history)
Phrase.create!(english: 'Do you see it constantly or sometimes not at all?', traditional: '你能一直看的到它或者是有時一點都看不到？', pinyin: 'nǐ néng yī zhí kàn de dào tā huò zhě shì yǒu shí yī diǎn dōu kàn bù dào', list: history)
Phrase.create!(english: 'Do you see anything appearing like a snowfall?', traditional: '你有沒有看東西看起來像下雪一樣？', pinyin: 'nǐ yǒu méi yǒu kàn dōng xī kàn qǐ lái xiàng xià xuě yī yàng', list: history)
Phrase.create!(english: 'Do you see a dark cloud or have you seen one?', traditional: '你有沒有看過黑色隂影？', pinyin: 'nǐ yǒu méi yǒu kàn guò hēi sè yīn yǐng', list: history)
Phrase.create!(english: 'At times, do the objects appear distorted?', traditional: '有時候東西會不會看起來很扭曲？', pinyin: 'yǒu shí hòu dōng xī huì bù huì kàn qǐ lái hěn niǔ qū', list: history)
Phrase.create!(english: 'For how long did you see it?', traditional: '你看到這個東西有多久了？', pinyin: 'nǐ kàn dào zhè gè dōng xī yǒu duō jiǔ le', list: history)
Phrase.create!(english: 'Does it seem like a shade is being held over your eyes?', traditional: '在看東西時會不會像戴帽子一樣有帽沿遮擋你的視線？', pinyin: 'zài kàn dōng xī shí huì bù huì xiàng dài mào zi yī yàng yǒu mào yán zhē dǎng nǐ de shì xiàn', list: history)
Phrase.create!(english: 'I would like to dilate your pupils in order to examine the inside.', traditional: '我想要使膨脹你的瞳孔來檢查你的眼睛內面。', pinyin: 'wǒ xiǎng yào shǐ péng zhàng nǐ de tóng kǒng lái jiǎn chá nǐ de yǎn jīng nèi miàn', list: internals)
Phrase.create!(english: 'You will not be able to see up close for a couple of hours, is that a problem?', traditional: '你幾個小時都不能看近的東西很清楚，這樣有沒有問題？', pinyin: 'nǐ jǐ gè xiǎo shí dōu bù néng kàn jìn de dōng xī hěn qīng chǔ zhè yàng yǒu méi yǒu wèn tí', list: internals)
Phrase.create!(english: 'I am going to put drops in your eyes.', traditional: '我現在就放眼藥了。', pinyin: 'wǒ xiàn zài jiù fàng yǎn yào le', list: internals)
Phrase.create!(english: 'Look at the red light.', traditional: '看著紅燈。', pinyin: 'kàn zhe hóng dēng', list: internals)
Phrase.create!(english: 'Look up.', traditional: '往上看。', pinyin: 'wǎng shàng kàn', list: internals)
Phrase.create!(english: 'Look down.', traditional: '往下看。', pinyin: 'wǎng xià kàn', list: internals)
Phrase.create!(english: 'Look up and to the right.', traditional: '往東北方向看。', pinyin: 'wǎng dōng běi fāng xiàng kàn', list: internals)
Phrase.create!(english: 'Look up and to the left.', traditional: '往西北方向看。', pinyin: 'wǎng xī běi fāng xiàng kàn', list: internals)
Phrase.create!(english: 'Look down and to the right.', traditional: '往東南方向看。', pinyin: 'wǎng dōng nán fāng xiàng kàn', list: internals)
Phrase.create!(english: 'Look down and to the left.', traditional: '往西南方向看。', pinyin: 'wǎng xī nán fāng xiàng kàn', list: internals)
Phrase.create!(english: 'Twelve', traditional: '十二', pinyin: 'shí èr', list: ishihara)
Phrase.create!(english: 'Eight', traditional: '八', pinyin: 'bā', list: ishihara)
Phrase.create!(english: 'Three', traditional: '三', pinyin: 'sān', list: ishihara)
Phrase.create!(english: 'Twenty nine', traditional: '二十九', pinyin: 'èr shí jiǔ', list: ishihara)
Phrase.create!(english: 'Seventy', traditional: '七十', pinyin: 'qī shí', list: ishihara)
Phrase.create!(english: 'Five', traditional: '五', pinyin: 'wǔ', list: ishihara)
Phrase.create!(english: 'Two', traditional: '二', pinyin: 'èr', list: ishihara)
Phrase.create!(english: 'Fifteen', traditional: '十五', pinyin: 'shí wǔ', list: ishihara)
Phrase.create!(english: 'Seventeen', traditional: '十七', pinyin: 'shí qī', list: ishihara)
Phrase.create!(english: 'Seventy four', traditional: '七十四', pinyin: 'qī shí sì', list: ishihara)
Phrase.create!(english: 'Twenty one', traditional: '二十一', pinyin: 'èr shí yī', list: ishihara)
Phrase.create!(english: 'Six', traditional: '六', pinyin: 'liù', list: ishihara)
Phrase.create!(english: 'Forty five', traditional: '四十五', pinyin: 'sì shí wǔ', list: ishihara)
Phrase.create!(english: 'Seven', traditional: '七', pinyin: 'qī', list: ishihara)
Phrase.create!(english: 'Sixteen', traditional: '十六', pinyin: 'shí liù', list: ishihara)
Phrase.create!(english: 'Seventy three', traditional: '七十三', pinyin: 'qī shí sān', list: ishihara)
Phrase.create!(english: 'Twenty six', traditional: '二十六', pinyin: 'èr shí liù', list: ishihara)
Phrase.create!(english: 'Forty two', traditional: '四十二', pinyin: 'sì shí èr', list: ishihara)
Phrase.create!(english: 'Four', traditional: '四', pinyin: 'sì', list: ishihara)
Phrase.create!(english: 'Put your chin here.', traditional: '請把你的下巴放在這。', pinyin: 'qǐng bǎ nǐ de xià bā fàng zài zhè', list: keratometry)
Phrase.create!(english: 'Look towards the center of the tube.', traditional: '看著管子的中間。', pinyin: 'kàn zhe guǎn zi de zhōng jiān', list: keratometry)
Phrase.create!(english: 'It is very important that you keep your forehead against the instrument.', traditional: '把你的額頭靠著這個儀器是很重要的。', pinyin: 'bǎ nǐ de é tóu kào zhù zhè gè yí qì shì hěn zhòng yào de', list: keratometry)
Phrase.create!(english: 'Open your eyes very wide.', traditional: '把你的眼睛開的很大。', pinyin: 'bǎ nǐ de yǎn jīng kāi de hěn dà', list: keratometry)
Phrase.create!(english: 'Don\'t move your head.', traditional: '別動你的頭。', pinyin: 'bié dòng nǐ de tóu', list: keratometry)
Phrase.create!(english: 'Try not to move your head and eyes.', traditional: '不要動你的頭和眼睛。', pinyin: 'bú yào dòng nǐ de tóu hé yǎn jīng', list: keratometry)
Phrase.create!(english: 'Don\'t blink.', traditional: '別眨眼。', pinyin: 'bié zhǎ yǎn', list: keratometry)
Phrase.create!(english: 'Look at my ear.', traditional: '看著我的耳朵。', pinyin: 'kàn zhe wǒ de ěr duǒ', list: keratometry)
Phrase.create!(english: 'Do you see this second line of letters?', traditional: '你能不能看到第二行字母？', pinyin: 'nǐ néng bù néng kàn dào dì èr háng zì mǔ', list: phorias)
Phrase.create!(english: 'Is it to the right or to the left?', traditional: '這是靠右邊還是左邊？', pinyin: 'zhè shì kào yòu biān hái shì zuǒ biān', list: phorias)
Phrase.create!(english: 'Or is it directly underneath?', traditional: '還是直接在下面？', pinyin: 'hái shì zhí jiē zài xià miàn', list: phorias)
Phrase.create!(english: 'Tell me when it is directly underneath.', traditional: '它到這個東西下面就告訴我。', pinyin: 'tā dào zhè gè dōng xī xià miàn jiù gào sù wǒ', list: phorias)
Phrase.create!(english: 'Do you see this second line?', traditional: '你能不能看到第二行？', pinyin: 'nǐ néng bù néng kàn dào dì èr háng', list: phorias)
Phrase.create!(english: 'Is it on the top or bottom?', traditional: '它在上面還是下面？', pinyin: 'tā zài shàng miàn hái shì xià miàn', list: phorias)
Phrase.create!(english: 'Or is it next to it?', traditional: '還是在旁邊？', pinyin: 'hái shì zài páng biān', list: phorias)
Phrase.create!(english: 'Now you have to look through a little hole.', traditional: '你現在從這個小洞看過去', pinyin: 'nǐ xiàn zài cóng zhè gè xiǎo dòng kàn guò qù', list: pinhole)
Phrase.create!(english: 'Tell me if the letters are clearer than they were before.', traditional: '請告訴我，現在的字母有沒有比以前的清楚。', pinyin: 'qǐng gào sù wǒ   xiàn zài de zì mǔ yǒu méi yǒu bǐ yǐ qián de qīng chǔ', list: pinhole)
Phrase.create!(english: 'Cover your left/right eye.', traditional: '遮住你的左/右眼睛。', pinyin: 'zhē zhù nǐ de zuǒ   yòu yǎn jīng', list: preliminaries)
Phrase.create!(english: 'Please read the smallest letters you can see.', traditional: '請你閱讀你能看到最小的字。', pinyin: 'qǐng nǐ yuè dú nǐ néng kàn dào zuì xiǎo de zì', list: preliminaries)
Phrase.create!(english: 'Please look at the letter.', traditional: '請看著這個字母。', pinyin: 'qǐng kàn zhe zhè gè zì mǔ', list: preliminaries)
Phrase.create!(english: 'Please fixate on this and tell me if it doubles.', traditional: '請注視看著這個東西。如果它雙重，請告訴我。', pinyin: 'qǐng zhù shì kàn zhe zhè gè dōng xī   rú guǒ tā shuāng chóng qǐng gào sù wǒ', list: preliminaries)
Phrase.create!(english: 'Now tell me when you see one.', traditional: '你看到一個就告訴我。', pinyin: 'nǐ kàn dào yī gè jiù gào sù wǒ', list: preliminaries)
Phrase.create!(english: 'Please look at these letters and tell me when they blur.', traditional: '請看著這些字母。如果它們變得模糊的，就告訴我。', pinyin: 'qǐng kàn zhe zhè xiē zì mǔ   rú guǒ tā men biàn dé mó hú de   jiù gào sù wǒ', list: preliminaries)
Phrase.create!(english: 'Please follow my light with your eyes without moving your head.', traditional: '請你不要動你的頭，只用眼睛跟著這個燈。', pinyin: 'qǐng nǐ bú yào dòng nǐ de tóu   zhǐ yòng yǎn jīng gēn zhù zhè gè dēng', list: preliminaries)
Phrase.create!(english: 'Please look straight ahead and ignore my light.', traditional: '請直接看前面，不要管我的燈。', pinyin: 'qǐng zhí jiē kàn qián miàn   bú yào guǎn wǒ de dēng', list: preliminaries)
Phrase.create!(english: 'Please cover you left/right eye and look at my nose.', traditional: '請你遮住你的左/右眼睛也看著我的鼻子。', pinyin: 'qǐng nǐ zhē zhù nǐ de zuǒ   yòu yǎn jīng yě kàn zhe wǒ de bí zi', list: preliminaries)
Phrase.create!(english: 'Tell me when you first see this.', traditional: '你一看到就告訴我。', pinyin: 'nǐ yī kàn dào jiù gào sù wǒ', list: preliminaries)
Phrase.create!(english: 'Please look at my open eye.', traditional: '請看著我已經開的眼睛。', pinyin: 'qǐng kàn zhe wǒ yǐ jīng kāi de yǎn jīng', list: preliminaries)
Phrase.create!(english: 'Please tell me what you see.', traditional: '請告訴我你看到什麼。', pinyin: 'qǐng gào sù wǒ nǐ kàn dào shén me', list: preliminaries)
Phrase.create!(english: 'Place your chin here.', traditional: '請把你的下巴放在這。', pinyin: 'qǐng bǎ nǐ de xià bā fàng zài zhè', list: preliminaries)
Phrase.create!(english: 'Place your forehead here.', traditional: '請把你的額頭放在這。', pinyin: 'qǐng bǎ nǐ de é tóu fàng zài zhè', list: preliminaries)
Phrase.create!(english: 'Look into the center of the instrument.', traditional: '請看著儀器的中間。', pinyin: 'qǐng kàn zhe yí qì de zhōng jiān', list: preliminaries)
Phrase.create!(english: 'Keep both eyes open.', traditional: '請把雙眼都打開。', pinyin: 'qǐng bǎ shuāng yǎn dōu dǎ kāi', list: preliminaries)
Phrase.create!(english: 'Look at the letter \'E\'.', traditional: '看著\'E\'。', pinyin: 'kàn zhe', list: preliminaries)
Phrase.create!(english: 'Do not look at my light.', traditional: '別看我的燈。', pinyin: 'bié kàn wǒ de dēng', list: preliminaries)
Phrase.create!(english: 'Keep both eyes open.', traditional: '請把雙眼都打開。', pinyin: 'qǐng bǎ shuāng yǎn dōu dǎ kāi', list: preliminaries)
Phrase.create!(english: 'Read the smallest line of letters you can see.', traditional: '請閱讀你能看到的最小行字。', pinyin: 'qǐng yuè dú nǐ néng kàn dào de zuì xiǎo xíng zì', list: preliminaries)
Phrase.create!(english: 'Which is better, one or two?', traditional: '哪一個比較好、一還昰二?', pinyin: 'nǎ yī gè bǐ jiào hǎo   yī hái shì èr', list: preliminaries)
Phrase.create!(english: 'Looking only at the top line, which is better, one or two?', traditional: '只看著最高一行、哪一個比較好丶一還是二?', pinyin: 'zhǐ kàn zhe zuì gāo yī háng   nǎ yī gè bǐ jiào hǎo zhǔ yī hái shì èr', list: preliminaries)
Phrase.create!(english: 'Looking only at the bottom one, which is better, one or two?', traditional: '只看著最底一個丶哪一個比較好丶一還是二?', pinyin: 'zhǐ kàn zhe zuì dǐ yī gè zhǔ nǎ yī gè bǐ jiào hǎo zhǔ yī hái shì èr', list: preliminaries)
Phrase.create!(english: 'Which group of lines are darker, the vertical or horizontal ones?', traditional: '哪一堆線比較黑，竪子還是橫向？', pinyin: 'nǎ yī duī xiàn bǐ jiào hēi   shù zi hái shì héng xiàng', list: preliminaries)
Phrase.create!(english: 'Keep this line of letters clear', traditional: '把這行字看起來清楚。', pinyin: 'bǎ zhè xíng zì kàn qǐ lái qīng chǔ', list: preliminaries)
Phrase.create!(english: 'Say \'blurry\' when it first blurs.', traditional: '開始模糊的時候就說\'模糊\'。', pinyin: 'kāi shǐ mó hú de shí hòu jiù shuō   mó hú', list: preliminaries)
Phrase.create!(english: 'Can you make it in focus.', traditional: '能不能讓這個東西變清楚。', pinyin: 'néng bù néng ràng zhè gè dōng xī biàn qīng chǔ', list: preliminaries)
Phrase.create!(english: 'Cover your right eye.', traditional: '遮住你的右眼。', pinyin: 'zhē zhù nǐ de yòu yǎn', list: visual_acuity)
Phrase.create!(english: 'Cover your left eye.', traditional: '遮住你的左眼。', pinyin: 'zhē zhù nǐ de zuǒ yǎn', list: visual_acuity)
Phrase.create!(english: 'Read the smallest line you can.', traditional: '唸出你能看到最小的一行。', pinyin: 'niàn chū nǐ néng kàn dào zuì xiǎo de yī háng', list: visual_acuity)
Phrase.create!(english: 'How many fingers?', traditional: '幾隻手指頭？', pinyin: 'jǐ zhī shǒu zhǐ tóu', list: visual_acuity)
Phrase.create!(english: 'Is the hand moving?', traditional: '手有沒有在動？', pinyin: 'shǒu yǒu méi yǒu zài dòng', list: visual_acuity)
Phrase.create!(english: 'Do you see the light? Where?', traditional: '你看不看到光？在那裡？', pinyin: 'nǐ kàn bù kàn dào guāng   zài nà lǐ', list: visual_acuity)
